[general]
import = [
	# "~/.config/alacritty/catppuccin-mocha.toml"
	# "~/.config/alacritty/rose-pine.toml"
	"~/.config/alacritty/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
opacity = 1
blur = false

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12
