[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.90
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12
