[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
opacity = 0.5
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 12
