AddKeymap("n", "gr", VSCodeAction("editor.action.goToReferences"), "LSP: Show References")
AddKeymap("n", "gd", VSCodeAction("editor.action.revealDefinition"), "LSP: Show Definitions")
AddKeymap("n", "gD", VSCodeAction("editor.action.revealDeclaration"), "LSP: Go to Declaration")
AddKeymap("n", "gi", VSCodeAction("editor.action.goToImplementation"), "LSP: Show Implementations")
AddKeymap("n", "gt", VSCodeAction("editor.action.goToTypeDefinition"), "LSP: Show Type Definitions")
AddKeymap("n", "<leader>cf", VSCodeAction("editor.action.formatDocument"), "LSP: Code Format")
AddKeymap({ "n", "v" }, "<leader>ca", VSCodeAction("editor.action.quickFix"), "LSP: Code Actions")
AddKeymap({ "n", "v" }, "<leader>cl", VSCodeAction("codelens.showLensesInCurrentLine"), "LSP: Code Lens")
AddKeymap("n", "<leader>rn", VSCodeAction("editor.action.rename"), "LSP: Rename")
AddKeymap("n", "K", VSCodeAction("editor.action.showHover"), "LSP: Show documentation on hover")
AddKeymap("n", "<leader>k", VSCodeAction("editor.action.triggerParameterHints"), "LSP: Show signature help on hover")
AddKeymap("i", "<C-k>", VSCodeAction("editor.action.triggerParameterHints"), "LSP: Show signature help on hover")
AddKeymap("n", "<leader>fds", VSCodeAction("editor.action.accessibleViewGoToSymbol"), "LSP: Show Symbols in Document")
AddKeymap("n", "<leader>fas", VSCodeAction("workbench.action.showAllSymbols"), "LSP: Show Symbols in All Documents")

AddKeymap("n", "<leader>xw", VSCodeAction("workbench.actions.view.problems"), "Problems: Show")
AddKeymap("n", "[d", VSCodeAction("editor.action.marker.prev"), "Problems: Previous")
AddKeymap("n", "]d", VSCodeAction("editor.action.marker.next"), "Problems: Next")
